declare const styles: {
    bgRojo: string;
    bgVerde: string;
    bgAmarillo: string;
    bgAzul: string;
    estadoError: string;
    dialogBonito: string;
    checkBonito: string;
    formLoggin: string;
    titleModal: string;
    verEnTabla: string;
    CMScommon: string;
    buttonRelacionadas: string;
    relacionadas: string;
    colorfondo: string;
    container: string;
    divTarjetas: string;
    logginRgister: string;
    row: string;
    rowBoton: string;
    derecha: string;
    izquierda: string;
    notificacion: string;
    column: string;
    'ms-Grid': string;
    title: string;
    subTitle: string;
    description: string;
    espacioTabs: string;
    button: string;
    label: string;
    tdWrap: string;
    tdBotones: string;
    tdMaster: string;
    tdBool: string;
    errorSpan: string;
};
export default styles;
